version: "3.7"

services:
 frontend:
  image: timetracker-web
  build:
   context: ../../frontend
  ports:
   - 3000:3000
   - 35729:35729 #this port is needed for hot reload
  volumes:
   - ../../frontend:/app:rw
   - node_modules:/node_modules
 
 api:
  image: timetracker-api
  build:
   context: ../../api
   dockerfile: Dockerfile
  volumes:
   - ../../api:/tmp:rw
   
 server:
  image: tomcat:9.0-jdk11
  environment:
   - CATALINA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
  ports:
   - 8080:8080 #api is accessed via port 8080
   - 8000:8000 #port for attaching debugger
   - 8009:8009
  links:
   - db #the name of the link is also the host name that the database can be reached at
  volumes: 
   - ../../api/target/com.vormadal.timetracker-1.0.0.war:/usr/local/tomcat/webapps/ROOT.war:rw
 db:
  image: mongo:3.4
  #command: ./init.sh #--serviceExecutor adaptive # alternate option is synchronous . adaptive is new (and experimental) but should give better performance
  ports:
   - 27017:27017
  volumes:
   - /mnt/f/db/data:/data/db:rw
volumes:
 node_modules:
#docker-compose up --build

#
#docker run -it -v ${pwd}:/tmp timetracker-api
#docker run -it -v ${pwd}/db:/data/db mongo:3.6

# docker run -it timetracker-mongo sh # run shell in container
