language: java
jdk:
- oraclejdk11
script:
- yarn --cwd ./frontend
- mvn package -P "Build react app","Copy react app"
deploy:
  provider: heroku
  app: vormadal-timetracker
  api_key:
    secure: rMJIPlIpDQF0Wgqnb3aQZypU7DA3evHGB6cmfClmTRWKfc+MqtOokWLxQl9DIlBMlxqijGj0Co/RHBQ8tNqZMfPOJ9umufoawZ8DnpVqaLss9q/SEx1Vt4BqGxrf9kJtnv27sGA80pYh8Nr3ayZ4LP9jy+dwHwSLGM8ALyvMvSq3OAXbAMK58iZQHnpXoPmgdRVwyvMvs7uMYS7mKOmlhyCht2W+8yFjVdNvHr0dGvjWhOgUiJa5PdbjD2KrOV2FjN9qxXSJzUXXrFJI6VrznJ/F8XyDSzpEM5Bm+Wg7fBMFF267cAB32Nr1VCNl2S4xYQcietF+3WxfR23wciwLbBofmKGy06an/pH+iFkU/15H7qWt4e47WWnjncgjifIaok+EVOuZlBN71e8Zz5kHhmxADl+7yS13dpINsSKorfOimdpw+u1kOYuElZODeq32fn9LUNqMd799dR2AQYZB0UXv77Q79snOC5vxbfXQjAXNFbjoj0zCOnb73f0UNVbI0Twq7FUa5Ge5exs3T9QxDGsbThxCAuep44CFIaVXUsvMmLAE0ut0X8A1C3V+0SiusN2oS7q9u7OoiM9xKCcDcX1VwGFk1K6NYT1xc+Ns9EzU8/D7F4e7hx/kPk/Kbi3n4vvDLC0xP/lct5OJSjIUT4PyL1zY+IHkTV6WGVHDLVQ=
  on: master